apiVersion: v1
kind: ConfigMap
metadata:
  name: imgcolor-config
  namespace: j12t-alpha
data:
  ImgColorService.yml: |
    debug: True
    n_threads: 16
    insecure_ports:
      - "[::]:32055"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicleidentify-imgcolor
  labels:
    app: vehicleidentify-imgcolor
  namespace: j12t-alpha
spec:
  ports:
  - port: 32055
    targetPort: 32055
    # nodePort: 32055
    name: vehicleidentify-imgcolor
  - port: 9126
    targetPort: 9126
    name: telegraf
  type: NodePort
  selector:
    app: vehicleidentify-imgcolor
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vehicleidentify-imgcolor
  namespace: j12t-alpha
spec:
  selector:
    matchLabels:
      app: vehicleidentify-imgcolor
  serviceName: vehicleidentify-imgcolor
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicleidentify-imgcolor
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: vehicleidentify-imgcolor
        image: jerapiblannett/vehicleidentify-imgcolor:latest
        env:
        - name: VEHICLE_IDENTIFICATION_LOGFILE
          value: ./log/imgcolor.log
        ports:
        - containerPort: 32055
        volumeMounts:
        - name: vehicleidentify-storage
          mountPath: "/usr/run/VehicleIdentification"
          subPath: data
        - name: vehicleidentify-storage
          mountPath: "/usr/run/VehicleIdentification"
          subPath: log
        - name: imgcolor-config
          mountPath: "/usr/run/VehicleIdentification/config"
      - name: telegraf-agent
        image: telegraf:1.20
        ports:
        - containerPort: 9126
        volumeMounts:
        - name: telegraf-config
          mountPath: "/etc/telegraf"
      volumes:
      - name: vehicleidentify-storage
        persistentVolumeClaim:
          claimName: vehicleidentify-claim
      - name: telegraf-config
        configMap:
          name: telegraf-config
          defaultMode: 420
      - name: imgcolor-config
        configMap:
          name: imgcolor-config
          defaultMode: 420